# Generated by Django 3.0.2 on 2020-04-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('Phone', models.CharField(default='', max_length=70)),
                ('msg', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
